### ISSUE TITLE
UnhandledPromiseRejectionWarningが発生して処理が停止する

### ISSUE THREAD

**Issue by hideki-a** [hideki-a/axe-runner#14]
axeを注入するところでエラーが発生する。
```
(node:2835) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'level' of undefined
    at eval (eval at <anonymous> (:1:1), <anonymous>:17026:38)
    at Array.forEach (<anonymous>)
    at Check.headingOrderAfter [as after] (eval at <anonymous> (:1:1), <anonymous>:17019:15)
    at eval (eval at <anonymous> (:1:1), <anonymous>:19489:35)
    at Array.forEach (<anonymous>)
    at Rule.after (eval at <anonymous> (:1:1), <anonymous>:19486:19)
    at eval (eval at <anonymous> (:1:1), <anonymous>:19890:26)
    at Array.map (<anonymous>)
    at Audit.after (eval at <anonymous> (:1:1), <anonymous>:19885:26)
    at eval (eval at <anonymous> (:1:1), <anonymous>:20468:30)
    at ExecutionContext._evaluateInternal (/Users/Shared/Development/axe-runner/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Users/Shared/Development/axe-runner/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async /Users/Shared/Development/axe-runner/lib/runner.js:145:29
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2835) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2835) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hideki-a** [comment]
下記が根本的な問題のようだが、ひとまず`catch()`を追加してエラーが発生したことを通知することにする。
```
Error: Evaluation failed: TypeError: Cannot read property 'level' of undefined
    at eval (eval at <anonymous> (:1:1), <anonymous>:17026:38)
    at Array.forEach (<anonymous>)
    at Check.headingOrderAfter [as after] (eval at <anonymous> (:1:1), <anonymous>:17019:15)
    at eval (eval at <anonymous> (:1:1), <anonymous>:19489:35)
    at Array.forEach (<anonymous>)
    at Rule.after (eval at <anonymous> (:1:1), <anonymous>:19486:19)
    at eval (eval at <anonymous> (:1:1), <anonymous>:19890:26)
    at Array.map (<anonymous>)
    at Audit.after (eval at <anonymous> (:1:1), <anonymous>:19885:26)
    at eval (eval at <anonymous> (:1:1), <anonymous>:20468:30)
    at ExecutionContext._evaluateInternal (/Users/Shared/Development/axe-runner/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Users/Shared/Development/axe-runner/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async /Users/Shared/Development/axe-runner/lib/runner.js:145:29
```
